### ISSUE TITLE
Update product docs with x-channel info

### ISSUE THREAD

**Issue by gueroJeff** [mozilla-l10n/documentation#107]
Update all Firefox and Firefox for Android documents to reflect the process and technical changes with implementing x-channel.

Includes:
* [ ] l10n.toml file (project configuration) when adding new locales

**Comment by flodolo** [comment]
Added l10n.toml file here. Note that we don't mention sign-offs anywhere in the docs.

**Comment by Delphine** [comment]
Updated Android in #116
