### ISSUE TITLE
Add exclude-multi-locale to mobile documentation

### ISSUE THREAD

**Issue by flodolo** [mozilla-l10n/documentation#121]
See https://bugzilla.mozilla.org/show_bug.cgi?id=1422249

We need to update the documentation:
* When adding a new locale, it needs to be added to exclude-multi-locale
* When moving it to beta, it needs to be removed from that list

**Comment by Delphine** [comment]
Got this! I wanna chat with you in Austin to make sure I get it all :) I think it's mostly clear, but just in case.

**Comment by Delphine** [comment]
This totally slipped on my radar. Putting it back up there :)
