### ISSUE TITLE
android-l10n new pages are blank

### ISSUE THREAD

**Issue by flodolo** [mozilla-l10n/documentation#169]
https://mozilla-l10n.github.io/documentation/products/android_l10n/index.html
https://mozilla-l10n.github.io/documentation/products/android_l10n/adding_new_locales.html

Both pages show up blank. I need to check locally what's going on.

@Delphine 
Can I also shorten the sidebar link to `Adding new locales`?

**Comment by Delphine** [comment]
> https://mozilla-l10n.github.io/documentation/products/android_l10n/index.html
> https://mozilla-l10n.github.io/documentation/products/android_l10n/adding_new_locales.html
> 
> Both pages show up blank. I need to check locally what's going on.
> 
> @Delphine
> Can I also shorten the sidebar link to `Adding new locales`?

Yes sure! (weird, I thought I had already shortened it)
