### ISSUE TITLE
Process for onboarding a new product needed

### ISSUE THREAD

**Issue by gueroJeff** [mozilla-l10n/documentation#185]
We need to document the process for onboarding a new product. Some general steps could include:
1) Do a full review of the FTL file. Check if the are strings missing comments, unclear content, etc. For sure they're using variables without any comment
2) Check for Fluent issues (what are common issues?)
3) Set automated review on pull requests that touch the FTL file, so that everything exposed in Pontoon is reviewer (via CODE_OWNERS)
4) Set up the project on Pontoon stage and very that it works
5) Set up prod

Some (potential) questions to ask about the product:
1) How will it be tested by localizers?
2) How do users select languages?
3) Do all the features allow for a consistent language UX if the product is localized? If not, what's missing and how deep should l10n go?

**Comment by flodolo** [comment]
I think this is covered by existing documents, e.g.
https://firefox-source-docs.mozilla.org/l10n/fluent/review.html
https://mozilla-l10n.github.io/documentation/misc/creating_new_repository.html
https://mozilla-l10n.github.io/documentation/tools/pontoon/adding_new_project.html

Plus Mana page on requesting product (community).
