### ISSUE TITLE
Document adding localizations to Firefox Desktop

### ISSUE THREAD

**Issue by Pike** [mozilla-l10n/documentation#196]
Is https://mozilla-l10n.github.io/documentation/products/firefox_desktop/adding_pontoon.html all we have on adding locales to desktop?

I got the question from @jfx2006 about how to add locales to TB, and didn't find what I was looking for.

There's also https://github.com/mozilla-l10n/pm-projects/projects/1, but that's not documented?

@flodolo ?

**Comment by flodolo** [comment]
Why https://github.com/mozilla-l10n/pm-projects/projects/1 should be documented? That's my personal way to track locales and requests, Delphine has private spreadsheets for example.

While we should remove the BitBucket reference from that doc, the process is documented in the Nightly builds section, when most of the work happens.
https://mozilla-l10n.github.io/documentation/products/firefox_desktop/adding_nightly.html

To add the locale to Firefox in Pontoon, you literally need an hg repo and the locale set up in Pontoon.

**Comment by flodolo** [comment]
BitBucket reference fixed in #197. I don't think that my personal project should be documented in there, as are the many scripts that I use to track errors, or completion levels.
