### ISSUE TITLE
Desktop search plugins documentation

### ISSUE THREAD

**Issue by Pike** [mozilla-l10n/documentation#199]
https://mozilla-l10n.github.io/documentation/products/searchplugins/setup_searchplugins.html has a bunch of legacy information that's not relevant anymore, right?

CC @flodolo

**Comment by flodolo** [comment]
Actually, the document should be updated. 

The summary at the beginning is likely hard-coded, and wrong at this point. Is there anything else that needs to be changed in the doc?

**Comment by flodolo** [comment]
Wait, the summary is not obsolete. 

I left the Wikipedia part there, because it's still useful when filing bugs for brand new locales. Same goes in case we need to create new searchplugins and need icons.

**Comment by flodolo** [comment]
Update was done here
https://github.com/mozilla-l10n/documentation/pull/190

If you find any specific detail that needs to be updated, please reopen.

**Comment by flodolo** [comment]
(Still going to reorganize the doc a bit, because the currently structure is a bit confusing as a result of all the cuts)

**Comment by flodolo** [comment]
I see at least a couple of things that should be updated, keeping issue open for now :)
