### ISSUE TITLE
iOS review: add notes about translations removal

### ISSUE THREAD

**Issue by flodolo** [mozilla-l10n/documentation#251]
Not only [this PR](https://github.com/mozilla-l10n/firefoxios-l10n/pull/124) is removing translations for some locales (known issue), but it's removing translations approved in the past 2 weeks. 

This needs to be called out [in this doc](https://github.com/mozilla-l10n/documentation/blob/main/src/products/iOS_products/review_iOSstrings.md), and we need to make sure the iOS team understands they're working on a live repository, especially when we exposed new strings only a few days prior.

**Comment by Delphine** [comment]
Should be addressed by https://github.com/mozilla-l10n/documentation/pull/275

**Comment by Delphine** [comment]
Closing as this is obsolete.
