### ISSUE TITLE
Document for hg wip lacks revsetalias

### ISSUE THREAD

**Issue by arai-a** [mozilla-l10n/documentation#256]
https://github.com/mozilla-l10n/documentation/blob/main/src/tools/mercurial/setting_mercurial_environment.md#mercurial-configuration-1

The document for `hg wip` lacks `revsetalias` and running the command results in error.
```
[revsetalias]
wip = (parents(not public()) or not public() or . or (head() and branch(default))) and (not obsolete() or orphan()^) and not closed() and not (fxheads() - date(-90))
```

**Comment by flodolo** [comment]
That's correct. Do you want to make a PR to fix it?

**Comment by arai-a** [comment]
Yes, opened https://github.com/mozilla-l10n/documentation/pull/257
