### ISSUE TITLE
Cover word-break in best practices

### ISSUE THREAD

**Issue by flodolo** [mozilla-l10n/documentation#267]
https://mozilla-l10n.github.io/documentation/localization/dev_best_practices.html#create-localizable-ui

We should also discourage the use of word-break, and point out that some languages (German) have very long words.

**Comment by flodolo** [comment]
@bcolsson Is this something you would have time to work on?

Here's an issue for example
https://github.com/mozilla/blurts-server/issues/2684

**Comment by bcolsson** [comment]
@flodolo - yep can do, I'll aim to get something done by next week.
