### ISSUE TITLE
Add new locale on iOS (build config, prerequisites)

### ISSUE THREAD

**Issue by Delphine** [mozilla-l10n/documentation#32]

**Comment by Delphine** [comment]
This seems to have been covered by flod in #37 (thanks :D)

**Comment by flodolo** [comment]
Wait, this is confusing.

#37 it's an issue (not a PR) that was closed in favor of this one.

**Comment by flodolo** [comment]
I think you fixed this in #78

**Comment by Delphine** [comment]
Ah right, thanks for remembering to update here
