### ISSUE TITLE
How Mozilla staff can request a new localization project

### ISSUE THREAD

**Issue by Delphine** [mozilla-l10n/documentation#33]
Content to come from here: https://docs.google.com/document/d/1gCDX7i-pLUYiGKt20Se4m3BLAIGUOb9hKpjcBfmbOaI/edit#

**Comment by flodolo** [comment]
Reference: https://wiki.mozilla.org/L10n:NewProjects

**Comment by gueroJeff** [comment]
We have incorporated this into our Mana documentation, where it is most discoverable to Mozilla staff.
