### ISSUE TITLE
Document to add/drop new locale on Android

### ISSUE THREAD

**Issue by flodolo** [mozilla-l10n/documentation#36]
New document.

Should include:
* Prerequisites (font, locale, CLDR support)
* Link to existing single/multi locale docs, when to add to which one
* Check to make sure that language appears in multilocale build the next day (https://bugzilla.mozilla.org/show_bug.cgi?id=1263437)

**Comment by Delphine** [comment]
Here is where I put:
* 1st check font support
* links to existing adding new locales to android (single and all-locales)

**Comment by flodolo** [comment]
I suppose this has become a WONTFIX at this point?

**Comment by Delphine** [comment]
Absolutely.
